name: "Get Diff Set in Repo"
on: push

env:
  PYTHON_VERSION: "3.11"

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changes.outputs.files }}

    steps:
      - name: Checkout by cloning last 2 commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changes
        run: |
          LAST_COMMIT_SHA=${{ github.event.before }}
          THIS_COMMIT_SHA=${{ github.sha }}
          CHANGES=$( \
            git diff --name-only --diff-filter=ACMRT $LAST_COMMIT_SHA $THIS_COMMIT_SHA | \
            grep "pages/.*.md$" | \
            xargs )
          echo "files=$CHANGES" >> $GITHUB_OUTPUT
          echo $CHANGES

  upload-artifacts:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: "1.6.1"

    steps:
      - name: Clone Processor Repo
        uses: actions/checkout@v4
        with:
          repository: tobytoyin/document-graph-processor
          token: ${{ secrets.DEPLOYMENT_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run poetry image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - run: ls -a .

      - name: Install & build
        run: |
          poetry build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: document-graph-processor
          path: |
            dist/*.whl

  run-processor-script:
    runs-on: ubuntu-latest
    needs: [changed-files, upload-artifacts]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/download-artifact@v3
        with:
          name: document-graph-processor
          path: ./libs

      - run: ls -a .

      - name: Install dependencies
        run: |
          pip3 install $( ls -d ./libs/* | grep .whl | xargs )

      - name: Run Processor CLI
        # if: ${{ needs.changed-files.outputs.files != "" }}
        run: |
          echo $NEO4J_URI
          export NEO4J_URI=$NEO4J_URI
          python3 -m doc_uploader.cli  --src obsidian  --dst neo4j --files ${{ needs.changed-files.outputs.files }}
        env: # Set the secret as an input
          NEO4J_URI: ${{ vars.NEO4J_URI }}
          NEO4J_USER: ${{ vars.NEO4J_USER }}
          NEO4J_PW: ${{ vars.NEO4J_PW }}
